### ISSUE TITLE
Doesn't work (at least not with Quod Libet 4.2.1)

### ISSUE THREAD

**Issue by beedaddy** [ijc/quodlibet-listenbrainz-plugin#1]
I just wanted to test this plugin. But it doesn't work. After complaining about "No module named 'StringIO'" I changed the according import line to `from io import StringIO`. Now, it says "No module named 'listenbrainz'". I don't know Python very well but my guess is that this plugin still is on python 2.7?

**Comment by beedaddy** [comment]
With `from . import listenbrainz` it seems to work now - at least it is now available in the plugin list.

**Comment by ijc** [comment]
I've been using it every day with Python 3 since Debian's quodlibet was updated, but it looks like I forgot a `git push` somewhere along the line, sorry.

I've just pushed the missing commit, hopefully that fixes things for you too.

**Comment by beedaddy** [comment]
Oh sorry, then forget my PR #2 :)
Thanks, I will try it.
